boolean Balia=false;
boolean DETH=false;
boolean ups3=false;
boolean ups2=false;
boolean Pup=false;
boolean Pup2=false;
boolean AUP=false;
boolean DUP=false;
boolean ups=false;
boolean SA=false;
float LY=height-25/2-10;
float Vol2=255;
float Vol=240;
float Vol3=0;
float level;
float EXP=0;
float exp=0;
float Rexp;
float SP=0;
float SC=0;
float Vol4;
float time;
float SC2;
float END;
float MLx;
float MLy;
float HAU;
float ho2;
float ho;
float ey;
int dethlevel;
int timelock;
int LEVEL=5;
int ITEM=10;
int denger;
int GH=100;
int FRt=0;
int Prt=0;
int Trt=5;
int Stt=0;
int Mrt=0;
int Xxt=0;
int ATK=3;
int DEF=0;
int SK2=0;
int DT=0;
int HG=1;
int SOP;
int AA2;
int HL=1;
int AL=1;
int DL=1;
void mouseWheel(MouseEvent event){
  float e = event.getCount();
  ey=e;
  SC=SC+e*Con2;
  SC=constrain(SC,0,2000);
  if(scene>=3)LY=LY+e*2;
  if(scene2==-1&&scene==1&&height<1520){
  HAU=HAU-e*10;
  HAU=constrain(HAU,-(1520-height),0);
}}
